- name: setup sdn stack
  gather_facts: False
  hosts: all
  user: vagrant
  vars:
    mininet_install_args: 'nf'
  roles:
    - common
    - openvswitch
    - mininet
    - ryu

- name: start services
  hosts: all
  user: vagrant
  gather_facts: False
  tasks:
      - include: roles/openvswitch/tasks/start-ovs.yaml
