- name: bootstrap ovs compilation
  command: "chdir=/home/vagrant/sdn/ovs/ ./boot.sh
           creates=/home/vagrant/sdn/ovs/configure"
  register: bootstrap

- name: configure ovs
  command: "chdir=/home/vagrant/sdn/ovs/ {{ item }}"
  with_items:
    - ./configure
    - /usr/bin/make
  when: bootstrap.changed

- name: install userspace and kernel modules
  command: "chdir=/home/vagrant/sdn/ovs/ make install"
  with_items:
    - /usr/bin/make install
    - /usr/bin/make modules_install
  when: bootstrap.changed
  sudo: yes

- name: load ovs kernel module
  modprobe: name=openvswitch state=present
  when: bootstrap.changed
  sudo: yes

- name: create ovsdb directory
  file: path=/usr/local/etc/openvswitch
        state=directory

- name: create ovsdb
  command: chdir=/home/vagrant/sdn/ovs/ ovsdb-tool create /usr/local/etc/openvswitch/conf.db vswitchd/vswitch.ovsschema
           creates=/usr/local/etc/openvswitch/conf.db
  sudo: yes


