- name: install ovs dependencies
  apt: pkg={{ item }}
       state=present
  with_items:
    - autoconf
    - automake
    - libtool
    - libssl-dev
    - openssl
    - graphviz
  sudo: yes

- name: clone openvswitch source
  git: repo=https://github.com/openvswitch/ovs.git dest=/home/vagrant/sdn/ovs
       version={{ ovs_version|default('master') }}


- include: build-ovs.yaml
