- name: start ovsdb-server
  command: ovsdb-server --remote=punix:/usr/local/var/run/openvswitch/db.sock \
                 --remote=db:Open_vSwitch,Open_vSwitch,manager_options \
                --pidfile --detach
  sudo: yes


- name: init ovsdb
  command: ovs-vsctl --no-wait init
  sudo: yes


- name: start ovs-vswitchd
  command: ovs-vswitchd --pidfile --detach
  sudo: yes
