- name: Install apt python
  command: apt-get install -y python-apt
  register: result
  until: result.rc == 1 or result.stdout.find("already the newest") != -1
  sudo: yes

- name: install additional packages
  apt: pkg={{ item }} state=present
       update_cache=yes
       cache_valid_time=3600
  with_items:
    - git
    - bash-completion
    - htop
    - strace
    - python-virtualenv
    - tmux
    - vim
  sudo: yes

- name: create sdn venv
  command: virtualenv sdn

- name: add vimrc
  copy: src=vimrc dest=/home/vagrant/.vimrc

- name: add venv to bashrc
  lineinfile: dest=/home/vagrant/.bashrc
              line='source /home/vagrant/sdn/bin/activate'
              state=present